CREATE TABLE "gaf_viewer_faulttrace" (
    "id" serial NOT NULL PRIMARY KEY,
    "the_geom" geometry,
    "src_id" integer NOT NULL,
    "accuracy" integer,
    "ns_neotectonic_section_id" integer NOT NULL,
    "ns_fault_summary_id" integer,
    "ns_average_dip" varchar(64),
    "ns_is_active" boolean,
    "ns_is_episodic" boolean,
    "ns_surface_dip" varchar(64),
    "ns_name" varchar(96),
    "ns_aseismic_slip_factor" numeric(3, 2) NOT NULL,
    "ns_compiler_id" integer,
    "ns_completion_id" integer,
    "ns_contributor_id" integer,
    "ns_dip_dir" integer,
    "ns_disp" varchar(64),
    "ns_downthrown_side_id" integer,
    "ns_last_movement" varchar(64),
    "ns_length" varchar(64),
    "ns_lower_sm_depth" varchar(64),
    "ns_recurrence_interval" varchar(64),
    "ns_net_slip_rate" varchar(64),
    "ns_slip_type_id" integer,
    "ns_strike" integer,
    "ns_strike_slip_rate" varchar(64),
    "ns_upper_sm_depth" varchar(64),
    "ns_vert_slip_rate" varchar(64),
    "ns_created_date" timestamp with time zone,
    "ns_modified_date" timestamp with time zone,
    "fs_fault_summary_id" integer NOT NULL,
    "fs_aseismic_slip_factor" numeric(3, 2) NOT NULL,
    "fs_compiler_id" integer,
    "fs_completion_id" integer,
    "fs_contributor_id" integer,
    "fs_average_dip" varchar(64),
    "fs_dip_dir" integer,
    "fs_displacement" varchar(64),
    "fs_downthrown_side_id" integer,
    "fs_is_active" boolean,
    "fs_is_episodic" boolean,
    "fs_is_section_summary" boolean,
    "fs_last_movement" varchar(64),
    "fs_length" varchar(64),
    "fs_lower_sm_depth" varchar(64),
    "fs_name" varchar(96),
    "fs_recurrence_interval" varchar(64),
    "fs_strike_slip_rate" varchar(64),
    "fs_slip_type_id" integer,
    "fs_strike" integer,
    "fs_upper_sm_depth" varchar(64),
    "fs_created_date" timestamp with time zone,
    "fs_modified_date" timestamp with time zone,
    "fs_net_slip_rate" varchar(64),
    "fs_vert_slip_rate" varchar(64),
    "ns_net_slip_rate_comp" numeric(10, 4),
    "slip_type" varchar(64),
    CONSTRAINT enforce_dims_the_geom CHECK ((st_ndims(the_geom) = 2)),
    CONSTRAINT enforce_geotype_the_geom CHECK (((geometrytype(the_geom) = 'LINESTRING'::text) OR (the_geom IS NULL))),
    CONSTRAINT enforce_srid_the_geom CHECK ((st_srid(the_geom) = 4326))
)
;
