CREATE TABLE "gaf_viewer_faultsource" (
    "id" serial NOT NULL PRIMARY KEY,
    "the_geom" geometry,
    "src_id" integer NOT NULL,
    "fault_summary_id" integer,
    "aseismic_slip_factor" varchar(64) NOT NULL,
    "compiler_id" integer NOT NULL,
    "completion_id" integer,
    "contributor_id" integer NOT NULL,
    "dip" varchar(64) NOT NULL,
    "dip_dir" integer NOT NULL,
    "last_movement" varchar(64),
    "length" varchar(64),
    "lower_sm_depth" varchar(64),
    "magnitude" varchar(64) NOT NULL,
    "name" varchar(96) NOT NULL,
    "recurrence_interval" varchar(64),
    "slip_rate" varchar(64) NOT NULL,
    "slip_type_id" integer NOT NULL,
    "upper_sm_depth" varchar(64),
    "created_date" timestamp with time zone,
    "modified_date" timestamp with time zone,
    "tectonic_region" varchar(96) NOT NULL,
    "area" varchar(64),
    "width" varchar(64),
    "compiler_name" varchar(64) NOT NULL,
    "contributor_name" varchar(64) NOT NULL,
    "pref_magnitude" double precision,
    "pref_dip" integer,
    "pref_slip_rate" double precision,
    "pref_length" double precision,
    "pref_width" double precision,
    "pref_area" double precision,
    "pref_lsd" double precision,
    "pref_usd" double precision,
    "pref_recint" integer,
    "slip_type" varchar(64),
    CONSTRAINT enforce_dims_the_geom CHECK ((st_ndims(the_geom) = 2)),
    CONSTRAINT enforce_geotype_the_geom CHECK (((geometrytype(the_geom) = 'MULTIPOLYGON'::text) OR (the_geom IS NULL))),
    CONSTRAINT enforce_srid_the_geom CHECK ((st_srid(the_geom) = 4326))
)
;
